### ISSUE TITLE
datatype (nirs) is not valid

### ISSUE THREAD

**Issue by Zhenna** [mne-tools/mne-nirs#221]
![Screenshot 2020-12-09 at 10 45 07 AM](https://user-images.githubusercontent.com/11832578/101567449-c939ed00-3a0b-11eb-81e8-e46fa029eb18.png)

Hi, I encountered a problem running the "Group Level GLM" analysis. It seems that "nirs" is not supported.

**Comment by rob-luke** [comment]
You need to install the requirements as described in the requirement.txt and requirements_doc.txt files, or use the environment file if you use conda..

Specifically this issue is caused because the NIRS BIDS standard is still a work in progress. So you need to use the development branch of MNE-BIDS (try 'pip install https://codeload.github.com/rob-luke/mne-bids/zip/nirs'). But I suggest installing the required packages by using requirement.txt and requirements_doc.txt .

Please let me know if this helps.

**Comment by rob-luke** [comment]
@Zhenna did this work for you?

**Comment by Zhenna** [comment]
Thank you, Robert.

`pip install https://codeload.github.com/rob-luke/mne-bids/zip/nirs` solved the datatype problem. However, the data directory is not found. Please see the attached screenshots.

![Screenshot 2020-12-16 at 10 34 07 AM](https://user-images.githubusercontent.com/11832578/102297440-41fbf480-3f8a-11eb-97f7-4a5ca4c3ab93.png)
![Screenshot 2020-12-16 at 10 36 53 AM](https://user-images.githubusercontent.com/11832578/102297702-b0d94d80-3f8a-11eb-8b5f-88a2c99ff1d4.png)
![Screenshot 2020-12-16 at 10 37 18 AM](https://user-images.githubusercontent.com/11832578/102297714-b6369800-3f8a-11eb-9421-f5e186d78715.png)


![Screenshot 2020-12-16 at 10 34 53 AM](https://user-images.githubusercontent.com/11832578/102297502-5a6c0f00-3f8a-11eb-9d8d-af2cd0c5e73b.png)

**Comment by rob-luke** [comment]
That's just a path issue now. You'll have to make sure you are pointing to the directory that contains the data in the call to `BIDSPath`.
