### ISSUE TITLE
Only main documentation is building

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#449]
Currently only the main documentation is building. It would be good to get multisphinx working or create new steps in the release procedure to update previous versions of the docs.

FYI @larsoner

**Comment by larsoner** [comment]
@rob-luke if it's okay, I'll:

1. Port over the MNE-Python doc build infrastructure (i.e., only build `main` and `maint/0.2`, each pushing to its own subfolder of `mne-nirs` GH pages branch)
2. Remove all sphinx-multibuild stuff
3. Copy over the static docs from the `git` history of the GH pages branch so that links to things like 1.2.0 work
4. Change release notes to a wiki so that every change does not cause a commit/CI run
5. Update release notes with instructions for how to archive the current stable site

Is this plan okay with you?

If so, this plan will take care of this issue and #436

**Comment by rob-luke** [comment]
This would be amazing @larsoner , the closer we can mirror MNE-python infrastructure the better.

Except step 4, can we leave the procedure in the repo? As I often work from my laptop with spotty internet and like to have access to procedures still. But I'm only +0.8 on this, you can veto if you want.

**Comment by larsoner** [comment]
No it's okay, I can `[ci skip]`. It probably doesn't get changed too often so doesn't waste too many resources...

**Comment by rob-luke** [comment]
Thanks
