### ISSUE TITLE
Stable documentation not building

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#484]
@larsoner I released a new version of MNE-NIRS and followed the instructions in https://github.com/mne-tools/mne-nirs/blob/main/doc/release.md. Everything has gone smoothly, except a new stable docs was not deployed to https://github.com/mne-tools/mne-nirs/tree/gh-pages. Do you have any suggestions as to where I might have gone wrong?

**Comment by larsoner** [comment]
Probably this

https://github.com/mne-tools/mne-nirs/blob/38d5e34f06674fbb6a8b01f5e9985ceae11ef751/.circleci/config.yml#L236

I'll push a quick fix

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-nirs/commit/46c85d4ec179b37d321d9b56ebf789d8c676bd6b

**Comment by larsoner** [comment]
Looks like it deployed but there are some bugs remaining

<img width="206" alt="Screen Shot 2022-09-13 at 9 46 08 AM" src="https://user-images.githubusercontent.com/2365790/189959704-b723939c-ede1-4b69-b51a-4a893f0f5647.png">

Feel free to fix when you get a chance @rob-luke

**Comment by larsoner** [comment]
(I got that dropdown when I selected 0.3.0)

**Comment by rob-luke** [comment]
Thanks @larsoner ill address the remaining bug(s) and update the instructions to include your fix above. Thanks mate

**Comment by rob-luke** [comment]
Sorry to bug you again @larsoner 
It seems that the fix did not cause the stable docs to be built. Looking at https://github.com/mne-tools/mne-nirs/tree/gh-pages it shows that stable was last changed 6 months ago (dev was changed 3 days ago at last commit to main).
I guess this is why the dropdown is wrong. Could you take a look at why stable didn't get regenerated after the 0.3 release? I tried kicking the CI with a small push to the main/0.3 branch but that didnt work.

**Comment by larsoner** [comment]
No problem! I always look at CircleCI directly:

https://app.circleci.com/pipelines/github/mne-tools/mne-nirs

You can see that your most recent builds are failing:

https://app.circleci.com/pipelines/github/mne-tools/mne-nirs/2416/workflows/c28e631e-8676-4053-97f4-f61a1e5ef936/jobs/2454

It should set off alarm bells "zmq is broken" which maybe leads you to https://github.com/zeromq/pyzmq/issues/1764, https://github.com/zeromq/pyzmq/issues/1763, or https://github.com/mne-tools/mne-python/pull/11169

You should just take the fix from https://github.com/mne-tools/mne-python/pull/11169 for now...

... then notice that 0.3 hasn't tried to deploy at all yet. This is because this commit needs to be backported to maint/0.3:

https://github.com/mne-tools/mne-nirs/commit/46c85d4ec179b37d321d9b56ebf789d8c676bd6b

... which I should have done in the first place -- sorry about that!

**Comment by rob-luke** [comment]
@larsoner any chance youll be at the fNIRS conference so I can buy you a 🍺? Thanks mate, I will check out those links and let you know how I go.

**Comment by larsoner** [comment]
Unfortunately not, it'll have to wait :)

**Comment by rob-luke** [comment]
> Unfortunately not, it'll have to wait :)

too bad :( 

When backporting should I clone the mne-tools/mne-nirs and [then use git-cherry-pick](https://stackoverflow.com/a/1440192)? Or is it best to rewrite all the code and then open a new PR from your own fork?

Thanks for the help @larsoner

**Comment by larsoner** [comment]
I would cherry pick and push directly to the maint branch or open a PR from your fork with the upstream maint branch as the target, up to you

**Comment by rob-luke** [comment]
Looks like its working now. Thanks for the help
